<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Model\Video;
use Doctrine\ODM\MongoDB\Cursor;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends DocumentRepository
{
    /**
     * @param string $userId
     * @return Cursor
     */
    public function findProcessedVideo($userId)
    {
        return $this->createQueryBuilder()
            ->field('status')->notEqual(Video::STATUS_DONE)
            ->field('userId')->equals($userId)
            ->getQuery()
            ->execute();
    }

    /**
     * @param string $userId
     * @return Cursor
     */
    public function findReadyVideo($userId)
    {
        return $this->createQueryBuilder()
            ->field('status')->equals(Video::STATUS_DONE)
            ->field('userId')->equals($userId)
            ->getQuery()
            ->execute();
    }

    /**
     * @param $userId
     * @param $videoId
     * @return mixed
     */
    public function updateVideoStatusToScheduled($userId, $videoId)
    {
        return $this->createQueryBuilder()
            ->update()
            ->field('status')->set(Video::STATUS_SCHEDULED)
            ->field('status')->equals(Video::STATUS_FAILED)
            ->field('userId')->equals($userId)
            ->field('id')->equals($videoId)
            ->getQuery()
            ->execute();
    }
}
