imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    upload_directory: '%kernel.root_dir%/../web/video'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: yalantis
    document_managers:
        default:
            auto_mapping: true

nelmio_api_doc:
    motd:
        template: AppBundle::Components/motd.html.twig
    sandbox:
        accept_type: "application/json;version=1.0"
        body_format:
            formats: [ json, form ]
#            default_format: json
        request_format:
            method: accept_header
        authentication:
            delivery: header
            name:     X-AUTH-TOKEN
    swagger:
        api_base_path:        /api
        swagger_version:      '1.2'
        api_version:          '0.1'
        info:
            title:                Yalantis
            description:          'Yalantis api doc'
    cache:
        enabled: false
    name: Yalantis API

snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn: redis://%redis.endpoint%
        default:
            type: predis
            alias: default
            dsn: redis://%redis.endpoint%
            logging: %kernel.debug%
    session:
        client: session

fos_rest:
    cache_dir: '%kernel.cache_dir%/fos_rest'
    format_listener:
        rules:
            - { path: '^/api', priorities: [ json ], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    routing_loader:
        default_format: json
        include_format: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    allowed_methods_listener: true
    exception:
        enabled: true
        messages:
            'InvalidArgumentException': true
            'DomainException': true
    versioning:
        enabled: true
        resolvers:
            query: true # Query parameter: /users?version=v1
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'


jms_serializer:
    property_naming:
        separator:
        lower_case: true
    metadata:
      cache: file
      debug: "%kernel.debug%"
      file_cache:
        dir: "%kernel.cache_dir%/serializer"
      auto_detection: true